### ISSUE TITLE
Using RTModelProfile to capture value for an x/y location using only one level

### ISSUE THREAD

**Issue by rkertesz** [dannycbowman/cageo-rnomads#2]
The code in question looks for more than one level. If I am only using surface level, it returns character(0) and then nothing is populated in profile.data for the z-value:

`l.i <- sort(as.numeric(unlist(stringr::str_extract_all(gridded.data$levels, 
        "\\d+"))), index.return = TRUE, decreasing = TRUE)
    profile.data <- NULL
    for (k in seq_len(length(lat))) {
        profile.data[[k]] <- BuildProfile(gridded.data, lon[k], 
            lat[k], spatial.average)[l.i$ix, ]
    }`

Here is what I got when debugging

> Browse[3]> 
> debug: return(fcst.grid) 
> exiting from: ModelGrid(grib.data, resolution, grid.type = grid.type)

The above is from ModelGrid
The below is from RTModelProfile

> Browse[3]> 
> debug: l.i <- sort(as.numeric(unlist(stringr::str_extract_all(gridded.data$levels, 
>     "\d+"))), index.return = TRUE, decreasing = TRUE)
> Browse[2]> 
> debug: profile.data <- NULL
> Browse[2]> gridded.data$levels
> [1] "surface"
> Browse[2]> stringr::str_extract_all(gridded.data$levels, "\d+")
> [[1]]
> character(0)

This is the function that blows up.

> for (k in seq_len(length(lat))) {
>     profile.data[[k]] <- BuildProfile(gridded.data, lon[k], 
>       lat[k], spatial.average)[l.i$ix, ]
>   }

Do you think that I can say something like
"If the gridded.data doesn't contain "\d+" then just use the "surface" level"
Thoughts?
This is really cool stuff by the way. I went much deeper into this than I thought I would and I am liking what I see.

**Comment by rkertesz** [comment]
Apologies for posting this here. Please let me know if there is indeed a better place to post.

**Comment by dannycbowman** [comment]
I have a mailing list: rnomads-user@lists.r-forge.r-project.org, feel free
to post general questions there.  I'm in the middle of interviewing for
jobs and finishing my dissertation, but the issue you outlined above is
something that should be simple to fix. If I have a chance, I'll take a
look.  If you don't hear from me by mid March, send me another email!

2016-02-16 19:00 GMT-05:00 Ruben notifications@github.com:

**Comment by rkertesz** [comment]
I will post to mailing list. tracking down a subsequent bug but this seems to solve this problem OK.
I am just substituting the number 0 at the surface.
`body(RTModelProfile)[[7]] <- substitute(l.i <- sort(as.numeric(unlist(stringr::str_extract_all(sub("surface", 0, gridded.data$levels), "\\d+"))), index.return = TRUE, decreasing = TRUE))`
